// Generated by make_demo.py -- do not edit by hand.
// Angles use the processing convention: 0 deg = right, increasing
// counter-clockwise (straight ahead = 90 deg). The page displays them
// front-referenced instead: 0 deg = straight ahead, clockwise positive.
window.DEMO_MANIFEST = {
  "alphas": [
    "0",
    "0.2",
    "0.5",
    "0.8",
    "1"
  ],
  "alpha_labels": [
    "α = 0",
    "α = 0.2",
    "α = 0.5",
    "α = 0.8",
    "α = 1"
  ],
  "alpha_modes": [
    "EM",
    "MM",
    "MM",
    "MM",
    "PM"
  ],
  "methods": [
    {
      "key": "dsptat",
      "label": "DSP-TAT"
    },
    {
      "key": "compass",
      "label": "COMPASS"
    },
    {
      "key": "ltat",
      "label": "LTAT"
    }
  ],
  "cases": [
    {
      "id": "case1",
      "order": 1,
      "mode": "brir",
      "t60": "200",
      "target_angles": [
        70
      ],
      "inter_angles": [
        170
      ],
      "alphas": [
        "0",
        "0.2",
        "0.5",
        "0.8",
        "1"
      ],
      "alpha_labels": [
        "α = 0",
        "α = 0.2",
        "α = 0.5",
        "α = 0.8",
        "α = 1"
      ],
      "alpha_modes": [
        "EM",
        "MM",
        "MM",
        "MM",
        "PM"
      ],
      "methods": [
        "dsptat",
        "compass",
        "ltat"
      ],
      "groundtruth": [
        {
          "audio": "audio/case1/groundtruth_a000.mp3",
          "image": "audio/case1/groundtruth_a000.png"
        },
        {
          "audio": "audio/case1/groundtruth_a020.mp3",
          "image": "audio/case1/groundtruth_a020.png"
        },
        {
          "audio": "audio/case1/groundtruth_a050.mp3",
          "image": "audio/case1/groundtruth_a050.png"
        },
        {
          "audio": "audio/case1/groundtruth_a080.mp3",
          "image": "audio/case1/groundtruth_a080.png"
        },
        {
          "audio": "audio/case1/groundtruth_a100.mp3",
          "image": "audio/case1/groundtruth_a100.png"
        }
      ],
      "files": {
        "dsptat": [
          {
            "audio": "audio/case1/dsptat_a000.mp3",
            "image": "audio/case1/dsptat_a000.png"
          },
          {
            "audio": "audio/case1/dsptat_a020.mp3",
            "image": "audio/case1/dsptat_a020.png"
          },
          {
            "audio": "audio/case1/dsptat_a050.mp3",
            "image": "audio/case1/dsptat_a050.png"
          },
          {
            "audio": "audio/case1/dsptat_a080.mp3",
            "image": "audio/case1/dsptat_a080.png"
          },
          {
            "audio": "audio/case1/dsptat_a100.mp3",
            "image": "audio/case1/dsptat_a100.png"
          }
        ],
        "compass": [
          {
            "audio": "audio/case1/compass_a000.mp3",
            "image": "audio/case1/compass_a000.png"
          },
          {
            "audio": "audio/case1/compass_a020.mp3",
            "image": "audio/case1/compass_a020.png"
          },
          {
            "audio": "audio/case1/compass_a050.mp3",
            "image": "audio/case1/compass_a050.png"
          },
          {
            "audio": "audio/case1/compass_a080.mp3",
            "image": "audio/case1/compass_a080.png"
          },
          {
            "audio": "audio/case1/compass_a100.mp3",
            "image": "audio/case1/compass_a100.png"
          }
        ],
        "ltat": [
          {
            "audio": "audio/case1/ltat_a000.mp3",
            "image": "audio/case1/ltat_a000.png"
          },
          {
            "audio": "audio/case1/ltat_a020.mp3",
            "image": "audio/case1/ltat_a020.png"
          },
          {
            "audio": "audio/case1/ltat_a050.mp3",
            "image": "audio/case1/ltat_a050.png"
          },
          {
            "audio": "audio/case1/ltat_a080.mp3",
            "image": "audio/case1/ltat_a080.png"
          },
          {
            "audio": "audio/case1/ltat_a100.mp3",
            "image": "audio/case1/ltat_a100.png"
          }
        ]
      },
      "label": "Case 1"
    },
    {
      "id": "case2",
      "order": 2,
      "mode": "brir",
      "t60": "200",
      "target_angles": [
        70
      ],
      "inter_angles": [
        50
      ],
      "alphas": [
        "0",
        "0.2",
        "0.5",
        "0.8",
        "1"
      ],
      "alpha_labels": [
        "α = 0",
        "α = 0.2",
        "α = 0.5",
        "α = 0.8",
        "α = 1"
      ],
      "alpha_modes": [
        "EM",
        "MM",
        "MM",
        "MM",
        "PM"
      ],
      "methods": [
        "dsptat",
        "compass",
        "ltat"
      ],
      "groundtruth": [
        {
          "audio": "audio/case2/groundtruth_a000.mp3",
          "image": "audio/case2/groundtruth_a000.png"
        },
        {
          "audio": "audio/case2/groundtruth_a020.mp3",
          "image": "audio/case2/groundtruth_a020.png"
        },
        {
          "audio": "audio/case2/groundtruth_a050.mp3",
          "image": "audio/case2/groundtruth_a050.png"
        },
        {
          "audio": "audio/case2/groundtruth_a080.mp3",
          "image": "audio/case2/groundtruth_a080.png"
        },
        {
          "audio": "audio/case2/groundtruth_a100.mp3",
          "image": "audio/case2/groundtruth_a100.png"
        }
      ],
      "files": {
        "dsptat": [
          {
            "audio": "audio/case2/dsptat_a000.mp3",
            "image": "audio/case2/dsptat_a000.png"
          },
          {
            "audio": "audio/case2/dsptat_a020.mp3",
            "image": "audio/case2/dsptat_a020.png"
          },
          {
            "audio": "audio/case2/dsptat_a050.mp3",
            "image": "audio/case2/dsptat_a050.png"
          },
          {
            "audio": "audio/case2/dsptat_a080.mp3",
            "image": "audio/case2/dsptat_a080.png"
          },
          {
            "audio": "audio/case2/dsptat_a100.mp3",
            "image": "audio/case2/dsptat_a100.png"
          }
        ],
        "compass": [
          {
            "audio": "audio/case2/compass_a000.mp3",
            "image": "audio/case2/compass_a000.png"
          },
          {
            "audio": "audio/case2/compass_a020.mp3",
            "image": "audio/case2/compass_a020.png"
          },
          {
            "audio": "audio/case2/compass_a050.mp3",
            "image": "audio/case2/compass_a050.png"
          },
          {
            "audio": "audio/case2/compass_a080.mp3",
            "image": "audio/case2/compass_a080.png"
          },
          {
            "audio": "audio/case2/compass_a100.mp3",
            "image": "audio/case2/compass_a100.png"
          }
        ],
        "ltat": [
          {
            "audio": "audio/case2/ltat_a000.mp3",
            "image": "audio/case2/ltat_a000.png"
          },
          {
            "audio": "audio/case2/ltat_a020.mp3",
            "image": "audio/case2/ltat_a020.png"
          },
          {
            "audio": "audio/case2/ltat_a050.mp3",
            "image": "audio/case2/ltat_a050.png"
          },
          {
            "audio": "audio/case2/ltat_a080.mp3",
            "image": "audio/case2/ltat_a080.png"
          },
          {
            "audio": "audio/case2/ltat_a100.mp3",
            "image": "audio/case2/ltat_a100.png"
          }
        ]
      },
      "label": "Case 2"
    },
    {
      "id": "case3",
      "order": 3,
      "mode": "brir",
      "t60": "200",
      "target_angles": [
        50
      ],
      "inter_angles": [],
      "alphas": [
        "0",
        "0.2",
        "0.5",
        "0.8",
        "1"
      ],
      "alpha_labels": [
        "α = 0",
        "α = 0.2",
        "α = 0.5",
        "α = 0.8",
        "α = 1"
      ],
      "alpha_modes": [
        "EM",
        "MM",
        "MM",
        "MM",
        "PM"
      ],
      "methods": [
        "dsptat",
        "compass",
        "ltat"
      ],
      "groundtruth": [
        {
          "audio": "audio/case3/groundtruth_a000.mp3",
          "image": "audio/case3/groundtruth_a000.png"
        },
        {
          "audio": "audio/case3/groundtruth_a020.mp3",
          "image": "audio/case3/groundtruth_a020.png"
        },
        {
          "audio": "audio/case3/groundtruth_a050.mp3",
          "image": "audio/case3/groundtruth_a050.png"
        },
        {
          "audio": "audio/case3/groundtruth_a080.mp3",
          "image": "audio/case3/groundtruth_a080.png"
        },
        {
          "audio": "audio/case3/groundtruth_a100.mp3",
          "image": "audio/case3/groundtruth_a100.png"
        }
      ],
      "files": {
        "dsptat": [
          {
            "audio": "audio/case3/dsptat_a000.mp3",
            "image": "audio/case3/dsptat_a000.png"
          },
          {
            "audio": "audio/case3/dsptat_a020.mp3",
            "image": "audio/case3/dsptat_a020.png"
          },
          {
            "audio": "audio/case3/dsptat_a050.mp3",
            "image": "audio/case3/dsptat_a050.png"
          },
          {
            "audio": "audio/case3/dsptat_a080.mp3",
            "image": "audio/case3/dsptat_a080.png"
          },
          {
            "audio": "audio/case3/dsptat_a100.mp3",
            "image": "audio/case3/dsptat_a100.png"
          }
        ],
        "compass": [
          {
            "audio": "audio/case3/compass_a000.mp3",
            "image": "audio/case3/compass_a000.png"
          },
          {
            "audio": "audio/case3/compass_a020.mp3",
            "image": "audio/case3/compass_a020.png"
          },
          {
            "audio": "audio/case3/compass_a050.mp3",
            "image": "audio/case3/compass_a050.png"
          },
          {
            "audio": "audio/case3/compass_a080.mp3",
            "image": "audio/case3/compass_a080.png"
          },
          {
            "audio": "audio/case3/compass_a100.mp3",
            "image": "audio/case3/compass_a100.png"
          }
        ],
        "ltat": [
          {
            "audio": "audio/case3/ltat_a000.mp3",
            "image": "audio/case3/ltat_a000.png"
          },
          {
            "audio": "audio/case3/ltat_a020.mp3",
            "image": "audio/case3/ltat_a020.png"
          },
          {
            "audio": "audio/case3/ltat_a050.mp3",
            "image": "audio/case3/ltat_a050.png"
          },
          {
            "audio": "audio/case3/ltat_a080.mp3",
            "image": "audio/case3/ltat_a080.png"
          },
          {
            "audio": "audio/case3/ltat_a100.mp3",
            "image": "audio/case3/ltat_a100.png"
          }
        ]
      },
      "label": "Case 3"
    },
    {
      "id": "case4",
      "order": 4,
      "mode": "brir",
      "t60": "200",
      "target_angles": [
        70,
        100
      ],
      "inter_angles": [
        50
      ],
      "alphas": [
        "0",
        "0.2",
        "0.5",
        "0.8",
        "1"
      ],
      "alpha_labels": [
        "α = 0",
        "α = 0.2",
        "α = 0.5",
        "α = 0.8",
        "α = 1"
      ],
      "alpha_modes": [
        "EM",
        "MM",
        "MM",
        "MM",
        "PM"
      ],
      "methods": [
        "dsptat",
        "compass",
        "ltat"
      ],
      "groundtruth": [
        {
          "audio": "audio/case4/groundtruth_a000.mp3",
          "image": "audio/case4/groundtruth_a000.png"
        },
        {
          "audio": "audio/case4/groundtruth_a020.mp3",
          "image": "audio/case4/groundtruth_a020.png"
        },
        {
          "audio": "audio/case4/groundtruth_a050.mp3",
          "image": "audio/case4/groundtruth_a050.png"
        },
        {
          "audio": "audio/case4/groundtruth_a080.mp3",
          "image": "audio/case4/groundtruth_a080.png"
        },
        {
          "audio": "audio/case4/groundtruth_a100.mp3",
          "image": "audio/case4/groundtruth_a100.png"
        }
      ],
      "files": {
        "dsptat": [
          {
            "audio": "audio/case4/dsptat_a000.mp3",
            "image": "audio/case4/dsptat_a000.png"
          },
          {
            "audio": "audio/case4/dsptat_a020.mp3",
            "image": "audio/case4/dsptat_a020.png"
          },
          {
            "audio": "audio/case4/dsptat_a050.mp3",
            "image": "audio/case4/dsptat_a050.png"
          },
          {
            "audio": "audio/case4/dsptat_a080.mp3",
            "image": "audio/case4/dsptat_a080.png"
          },
          {
            "audio": "audio/case4/dsptat_a100.mp3",
            "image": "audio/case4/dsptat_a100.png"
          }
        ],
        "compass": [
          {
            "audio": "audio/case4/compass_a000.mp3",
            "image": "audio/case4/compass_a000.png"
          },
          {
            "audio": "audio/case4/compass_a020.mp3",
            "image": "audio/case4/compass_a020.png"
          },
          {
            "audio": "audio/case4/compass_a050.mp3",
            "image": "audio/case4/compass_a050.png"
          },
          {
            "audio": "audio/case4/compass_a080.mp3",
            "image": "audio/case4/compass_a080.png"
          },
          {
            "audio": "audio/case4/compass_a100.mp3",
            "image": "audio/case4/compass_a100.png"
          }
        ],
        "ltat": [
          {
            "audio": "audio/case4/ltat_a000.mp3",
            "image": "audio/case4/ltat_a000.png"
          },
          {
            "audio": "audio/case4/ltat_a020.mp3",
            "image": "audio/case4/ltat_a020.png"
          },
          {
            "audio": "audio/case4/ltat_a050.mp3",
            "image": "audio/case4/ltat_a050.png"
          },
          {
            "audio": "audio/case4/ltat_a080.mp3",
            "image": "audio/case4/ltat_a080.png"
          },
          {
            "audio": "audio/case4/ltat_a100.mp3",
            "image": "audio/case4/ltat_a100.png"
          }
        ]
      },
      "label": "Case 4"
    },
    {
      "id": "case5",
      "order": 5,
      "mode": "brir",
      "t60": "600",
      "target_angles": [
        70
      ],
      "inter_angles": [
        170
      ],
      "alphas": [
        "0",
        "0.2",
        "0.5",
        "0.8",
        "1"
      ],
      "alpha_labels": [
        "α = 0",
        "α = 0.2",
        "α = 0.5",
        "α = 0.8",
        "α = 1"
      ],
      "alpha_modes": [
        "EM",
        "MM",
        "MM",
        "MM",
        "PM"
      ],
      "methods": [
        "dsptat",
        "compass",
        "ltat"
      ],
      "groundtruth": [
        {
          "audio": "audio/case5/groundtruth_a000.mp3",
          "image": "audio/case5/groundtruth_a000.png"
        },
        {
          "audio": "audio/case5/groundtruth_a020.mp3",
          "image": "audio/case5/groundtruth_a020.png"
        },
        {
          "audio": "audio/case5/groundtruth_a050.mp3",
          "image": "audio/case5/groundtruth_a050.png"
        },
        {
          "audio": "audio/case5/groundtruth_a080.mp3",
          "image": "audio/case5/groundtruth_a080.png"
        },
        {
          "audio": "audio/case5/groundtruth_a100.mp3",
          "image": "audio/case5/groundtruth_a100.png"
        }
      ],
      "files": {
        "dsptat": [
          {
            "audio": "audio/case5/dsptat_a000.mp3",
            "image": "audio/case5/dsptat_a000.png"
          },
          {
            "audio": "audio/case5/dsptat_a020.mp3",
            "image": "audio/case5/dsptat_a020.png"
          },
          {
            "audio": "audio/case5/dsptat_a050.mp3",
            "image": "audio/case5/dsptat_a050.png"
          },
          {
            "audio": "audio/case5/dsptat_a080.mp3",
            "image": "audio/case5/dsptat_a080.png"
          },
          {
            "audio": "audio/case5/dsptat_a100.mp3",
            "image": "audio/case5/dsptat_a100.png"
          }
        ],
        "compass": [
          {
            "audio": "audio/case5/compass_a000.mp3",
            "image": "audio/case5/compass_a000.png"
          },
          {
            "audio": "audio/case5/compass_a020.mp3",
            "image": "audio/case5/compass_a020.png"
          },
          {
            "audio": "audio/case5/compass_a050.mp3",
            "image": "audio/case5/compass_a050.png"
          },
          {
            "audio": "audio/case5/compass_a080.mp3",
            "image": "audio/case5/compass_a080.png"
          },
          {
            "audio": "audio/case5/compass_a100.mp3",
            "image": "audio/case5/compass_a100.png"
          }
        ],
        "ltat": [
          {
            "audio": "audio/case5/ltat_a000.mp3",
            "image": "audio/case5/ltat_a000.png"
          },
          {
            "audio": "audio/case5/ltat_a020.mp3",
            "image": "audio/case5/ltat_a020.png"
          },
          {
            "audio": "audio/case5/ltat_a050.mp3",
            "image": "audio/case5/ltat_a050.png"
          },
          {
            "audio": "audio/case5/ltat_a080.mp3",
            "image": "audio/case5/ltat_a080.png"
          },
          {
            "audio": "audio/case5/ltat_a100.mp3",
            "image": "audio/case5/ltat_a100.png"
          }
        ]
      },
      "label": "Case 5"
    }
  ]
};
